package model.entities.critters.stats;

import main.Handler;
import model.entities.critters.Critter;

import java.util.Random;

public class StatsModule {

    private Handler handler;
    private Critter.Species species;
    private int level;

    /* statsIV: Each of these is used to determine their associated stat, with
    the hpIV determined from the IVs stored for the other four.

    As such, a Pokémon with
    an odd-number Attack IV
    has 8 added to its HP IV,
    an odd-number Defense IV
    has 4 added,
    an odd-number Speed IV
    has 2 added,
    and an odd-number Special IV
    has 1 added.

    IVs are fixed when it is generated by the game
    (i.e. when it is obtained as an Egg from the Pokémon Day Care,
    encountered in the wild, or given to the player by an NPC),
    and CANNOT be changed. */

    //(IV == individual value [GENES]... IVs range from 0-15)
    private final int attackIV, defenseIV, speedIV, specialIV, hpIV;

    //(EV == effort value [STATs EXPERIENCE]... EP == effort points)
    private int attackEP, defenseEP, speedEP, specialEP, hpEP;

    /* DETERMINATION OF STATS:
        hp =        ( ((((base + iv) * 2) + (sqrt(ev) / 4)) * level) / 100 ) + level + 10
        otherStat = ( ((((base + iv) * 2) + (sqrt(ev) / 4)) * level) / 100 ) + 5
        damage = ((((((2 * Level) / 5) + 2) * Power  * (A/D)) / 50) + 2) * Modifier
            Modifier == Targets * Weather * Badge * Critical * random * STAB * Type * Burn * other. */
    // STATS (attackBase, defenseBase, speedBase, and specialBase can be found in Critter.Species)

    private int attackEffective, defenseEffective, speedEffective, specialEffective, hpEffective;

    public StatsModule(Handler handler, Critter.Species species, int level) {
        this.handler = handler;
        this.species = species;
        this.level = level;

        Random random = new Random();
        //IVs
        attackIV = random.nextInt(16);
        defenseIV = random.nextInt(16);
        speedIV = random.nextInt(16);
        specialIV = random.nextInt(16);
        hpIV =  ((attackIV % 2 == 1)    ? 8 : 0) +
                ((defenseIV % 2 == 1)   ? 4 : 0) +
                ((speedIV % 2 == 1)     ? 2 : 0) +
                ((specialIV % 2 == 1)   ? 1 : 0);

        //EVs (EP == effort points)
        attackEP = 0;
        defenseEP = 0;
        speedEP = 0;
        specialEP = 0;
        hpEP = 0;

        attackEffective = updateAttackEffective(this.level);

        hpEffective = updateHpEffective(this.level);
    } // **** end StatsModule(Handler) constructor ****

    private int updateAttackEffective(int level) {
        int attackEffective = (int)((((((species.getAttackBase() + attackIV) * 2) + (Math.sqrt(attackEP) / 4)) * level) / 100) + 5);
        return attackEffective;
    }

    private int updateHpEffective(int level) {
        int hpEffective = (int)((((((species.getHpBase() + hpIV) * 2) + (Math.sqrt(hpEP) / 4)) * level) / 100) + level + 10);
        return hpEffective;
    }

    public void consoleOutIVsAndEVs(String nameColloquial) {
        System.out.println(nameColloquial + "'s attackIV: " + attackIV + ".");
        System.out.println(nameColloquial + "'s defenseIV: " + defenseIV + ".");
        System.out.println(nameColloquial + "'s speedIV: " + speedIV + ".");
        System.out.println(nameColloquial + "'s specialIV: " + specialIV + ".");
        System.out.println(nameColloquial + "'s hpIV: " + hpIV + ".");
        System.out.println("////////////////////////////////");
        System.out.println(nameColloquial + "'s attackEP: " + attackEP + ".");
        System.out.println(nameColloquial + "'s defenseEP: " + defenseEP + ".");
        System.out.println(nameColloquial + "'s speedEP: " + speedEP + ".");
        System.out.println(nameColloquial + "'s specialEP: " + specialEP + ".");
        System.out.println(nameColloquial + "'s hpEP: " + hpEP + ".");
    }

    // GETTERS AND SETTERS

    public int getHpEffective() { return hpEffective; }

} // *** end StatsModule class ****