package model.entities.critters;

import main.Handler;
import main.gfx.Assets;
import model.entities.critters.moves.MoveModule;

import java.awt.image.BufferedImage;
import java.util.Random;

public class Critter {

    private Handler handler;

    private Species species;
    private int level;

    private String nameColloquial;
    private int hpCurrent;
    private StatusConditionNonVolatile status;
    private int expCurrent, expRewardedIfDefeated;

    private MoveModule moveModule;

    // STATS (attackBase, defenseBase, speedBase, and specialBase can be found in Species)

    /* IV == individual value (GENES)
    "IVs range from 0-15.

    Each of these is used to determine their associated stat, with
    the HP IV determined from the IVs stored for the other four.

    As such, a Pokémon with
    an odd-number Attack IV
    has 8 added to its HP IV,
    an odd-number Defense IV
    has 4 added,
    an odd-number Speed IV
    has 2 added,
    and an odd-number Special IV
    has 1 added.

    IVs are fixed when it is generated by the game
    (i.e. when it is obtained as an Egg from the Pokémon Day Care,
    encountered in the wild, or given to the player by an NPC),
    and cannot be changed." */
    private int attackIV, defenseIV, speedIV, specialIV, hpIV;

    //(EV == effort value [STATs EXPERIENCE]... EP == effort points)
    private int attackEP, defenseEP, speedEP, specialEP, hpEP;

    public Critter(Handler handler, Species species, int level) {
        this.handler = handler;

        this.species = species;
        this.level = level;

        nameColloquial = this.species.toString().replace('_', ' ');
        status = StatusConditionNonVolatile.OK;
        expCurrent = 0;
        expRewardedIfDefeated = 10;

        moveModule = new MoveModule(handler);

        Random random = new Random();
        //IVs
        attackIV = random.nextInt(16);
        defenseIV = random.nextInt(16);
        speedIV = random.nextInt(16);
        specialIV = random.nextInt(16);
        hpIV =  ((attackIV % 2 == 1)    ? 8 : 0) +
                ((defenseIV % 2 == 1)   ? 4 : 0) +
                ((speedIV % 2 == 1)     ? 2 : 0) +
                ((specialIV % 2 == 1)   ? 1 : 0);

        //EVs (EP == effort points)
        attackEP = 0;
        defenseEP = 0;
        speedEP = 0;
        specialEP = 0;
        hpEP = 0;

        //TODO: should NOT be solo based on hpBase (should use equation that factors in hpIV).
        hpCurrent = (int)species.hpBase;
    } // **** end Critter(Handler, Species, int) constructor ****

    public void consoleOutIVsAndEVs() {
        System.out.println(nameColloquial + "'s attackIV: " + attackIV + ".");
        System.out.println(nameColloquial + "'s defenseIV: " + defenseIV + ".");
        System.out.println(nameColloquial + "'s speedIV: " + speedIV + ".");
        System.out.println(nameColloquial + "'s specialIV: " + specialIV + ".");
        System.out.println(nameColloquial + "'s hpIV: " + hpIV + ".");
        System.out.println("////////////////////////////////");
        System.out.println(nameColloquial + "'s attackEP: " + attackEP + ".");
        System.out.println(nameColloquial + "'s defenseEP: " + defenseEP + ".");
        System.out.println(nameColloquial + "'s speedEP: " + speedEP + ".");
        System.out.println(nameColloquial + "'s specialEP: " + specialEP + ".");
        System.out.println(nameColloquial + "'s hpEP: " + hpEP + ".");
    }

    public BufferedImage getSpeciesIcon() {
        return species.speciesIcon;
    }

    public String getNameColloquial() {
        return nameColloquial;
    }

    public int getLevel() {
        return level;
    }

    public int getHpCurrent() {
        return hpCurrent;
    }

    public Species getSpecies() {
        return species;
    }

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    public enum Species {
        THUNDER_MOUSE(25, 190, Type.ELECTRIC, Type.ELECTRIC, ExpGroup.MEDIUM_FAST, 35, 55, 30, 90, 50),
        TOTIPOTENT_PUPPY(133, 45, Type.NORMAL, Type.NORMAL, ExpGroup.MEDIUM_FAST, 55, 55, 50, 55, 65),
        COLONIAL_MOUSE(19, 255, Type.NORMAL, Type.NORMAL, ExpGroup.MEDIUM_FAST, 30, 56, 35, 72, 25),
        MOTLEY_PIGEON(16, 255, Type.NORMAL, Type.FLYING, ExpGroup.MEDIUM_SLOW, 40, 45, 40, 56, 35),
        COASTAL_GULL(21, 255, Type.NORMAL, Type.FLYING, ExpGroup.MEDIUM_FAST, 40, 60, 30, 70, 31),
        STONE_MONKEY(56, 190, Type.FIGHTING, Type.FIGHTING, ExpGroup.MEDIUM_FAST, 40, 80, 35, 70, 35),
        FEMALE_LAPINE(29, 235, Type.POISON, Type.POISON, ExpGroup.MEDIUM_SLOW, 55, 47, 52, 41, 40),
        MALE_LAPINE(32, 235, Type.POISON, Type.POISON, ExpGroup.MEDIUM_SLOW, 46, 57, 40, 50, 40),
        HOOKAH_CATERPILLAR(10, 255, Type.BUG, Type.BUG, ExpGroup.MEDIUM_FAST, 45, 30, 35, 45, 20),
        GRUB_LARVAE(13, 255, Type.BUG, Type.POISON, ExpGroup.MEDIUM_FAST, 40, 35, 30, 50, 20),
        GROUND_HOG(50, 255, Type.GROUND, Type.GROUND, ExpGroup.MEDIUM_FAST, 10, 55, 25, 95, 45),
        SAND_MOUSE(27, 255, Type.GROUND, Type.GROUND, ExpGroup.MEDIUM_FAST, 50, 75, 85, 40, 30),
        ROCK_GOLEM(74, 255, Type.ROCK, Type.GROUND, ExpGroup.MEDIUM_SLOW, 40, 80, 100, 20, 30),
        LEGLESS_ROCK_LIZARD(95, 45, Type.ROCK, Type.GROUND, ExpGroup.MEDIUM_FAST, 35, 45, 160, 70, 30),
        BEARHUG_PYTHON(23, 255, Type.POISON, Type.POISON, ExpGroup.MEDIUM_FAST, 35, 60, 44, 55, 40),
        SMOKEY_KITTY(52, 255, Type.NORMAL, Type.NORMAL, ExpGroup.MEDIUM_FAST, 40, 45, 35, 90, 40),
        GASEOUS_GOLEM(109, 190, Type.POISON, Type.POISON, ExpGroup.MEDIUM_FAST, 40, 65, 95, 35, 60),
        KARAOKE_CREAMPUFF(39, 170, Type.NORMAL, Type.NORMAL, ExpGroup.FAST, 115, 45, 20, 20, 25),
        SPLASHILIC_TILAPIA(129, 255, Type.WATER, Type.WATER, ExpGroup.SLOW, 20, 10, 55, 80, 20), //from AQUAPONIC SALESMAN in hospital near Place.MT_MOON.
        DINO_SPROUTLING(1, 45, Type.GRASS, Type.POISON, ExpGroup.MEDIUM_SLOW, 45, 49, 49, 45, 65);

        private final int id, catchRate;
        private Type type1, type2;
        private ExpGroup expGroup;
        //stats
        private final float hpBase, attackBase, defenseBase, speedBase, specialBase;
        //icon (method initializes speciesIcon with switch construct based on int id)
        private BufferedImage speciesIcon;

        /*
        The box trick is
        a method in the core series Pokémon games
        that causes a Pokémon's
        stats to be
        recalculated based on its
        current effort values.

        This trick is applicable in Generations I through IV; from Generation V onward,
        the trick is obsolete, due to changes to a Pokémon's EVs automatically being
        applied to its stats.

        A Pokémon's stats are derived values, based on the Pokémon's
        level, EVs (effort values), IVs (individual values), base stats,
        and (from Generation III onward) nature.
        If a Pokémon levels up or evolves,
        its level or base stats change,
        and all of its stats are recalculated;
        however, prior to Generation V, a Pokémon's
        stats are not always recalculated when its EVs are changed.
        From Generation I to IV, even if a Pokémon gains EVs in battle,
        its stats remain unchanged unless it leveled up or evolved;
        in Generation I and II, gaining EVs by consuming vitamins
        does not cause a Pokémon's stats to be recalculated either.

        If a Pokémon is placed in the PC,
        its stats will be recalculated,
        without the need to level up or evolve.
        Doing this intentionally is known as the box trick.
        This occurs because the derived stats
        are not stored for Pokémon in the PC, o
        nly the values from which they are derived.

        From Generation III onward,
        a Pokémon's stats are also
        recalculated if its EVs are changed by a vitamin or EV-reducing Berry.

        1	List of stats
            1.1	Permanent stats                 !!!!!!!!!!!
                1.1.1	Hit Points
                1.1.2	Attack
                1.1.3	Defense
                1.1.4	Special
                    1.1.4.1	Special Attack
                    1.1.4.2	Special Defense
                1.1.5	Speed
            1.2	In-battle stats                 !!!!!!!!!!!
                1.2.1	Evasion (see Stage [-6 to +6])
                1.2.2	Accuracy (see Stage [-6 to +6])

        2	Determination of stats
            2.1	Base stat values
            2.2	Level
            2.3	Nature
            2.4	Individual values
            2.5	Effort values
            2.6	Awakening values
            2.7	Formula
            2.8	In battle
                2.8.1	Accuracy and evasion
            2.9	Combat Power

        3	Stat modifiers
            3.1	In-battle modification
            3.2	Stage modification quotes
            3.3	Stage multipliers
         */

        Species(int id, int catchRate, Type type1, Type type2, ExpGroup expGroup,
                float hpBase, float attackBase, float defenseBase, float speedBase, float specialBase) {
            this.id = id;
            this.catchRate = catchRate;
            this.type1 = type1;
            this.type2 = type2;
            this.expGroup = expGroup;

            //stats
            this.hpBase = hpBase;
            this.attackBase = attackBase;
            this.defenseBase = defenseBase;
            this.speedBase = speedBase;
            this.specialBase = specialBase;

            //BufferedImage speciesIcon
            initSpeciesIcon();
        }

        //intentionally public in case BufferedImage has to be re-initialized after loading.
        public void initSpeciesIcon() {
            switch(id) {
                case 25: //THUNDER_MOUSE
                    speciesIcon = Assets.crittersBufferedImageNestedArray[2][0];
                    break;
                case 1: //DINO_SPROUTLING
                    speciesIcon = Assets.crittersBufferedImageNestedArray[0][0];
                    break;
                case 133: //TOTIPOTENT_PUPPY
                    speciesIcon = Assets.crittersBufferedImageNestedArray[11][0];
                    break;
                case 56: //STONE_MONKEY
                    speciesIcon = Assets.crittersBufferedImageNestedArray[4][7];
                    break;
                case 129: //SPLASHILIC_TILAPIA
                    speciesIcon = Assets.crittersBufferedImageNestedArray[10][8];
                    break;
                case 74: //ROCK_GOLEM
                    speciesIcon = Assets.crittersBufferedImageNestedArray[6][1];
                    break;
                case 21: //COASTAL_GULL
                    speciesIcon = Assets.crittersBufferedImageNestedArray[1][8];
                    break;
                default:
                    System.out.println("Critter.initSpeciesIcon() switch(id) construct's default block.");
                    System.out.println("THIS Critter is NOT listed in Critter.initSpeciesIcon()!!!");
                    speciesIcon = Assets.critterBallSprite;
                    break;
            }
        }

        public int getHpBase() { return (int)hpBase; }

    }

    public enum ExpGroup {
        FAST, MEDIUM_FAST, MEDIUM_SLOW, SLOW;
    }

    public enum Type {
        BUG,
        DRAGON,
        ELECTRIC,
        FIGHTING,
        FIRE,
        FLYING,
        GHOST,
        GRASS,
        GROUND,
        ICE,
        NORMAL,
        POISON,
        PSYCHIC,
        ROCK,
        WATER;
    }

    public enum StatusConditionNonVolatile {
        OK,
        BURN,
        FREEZE,
        PARALYSIS,
        POISON,
        BADLY_POISONED,
        SLEEP;
    }

    public enum StatusConditionVolatile {
        BOUND, CANT_ESCAPE, CONFUSION, CURSE, EMBARGO, ENCORE, FLINCH, HEAL_BLOCK, IDENTIFIED,
        INFATUATION, LEECH_SEED, NIGHTMARE, PERISH_SONG, TAUNT, TELEKINESIS, TORMENT;
    }

} // **** end Critter class ****